name: Solidity code coverage

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: IS_TEST_SOL_COV=1 npx hardhat coverage
